config/routes.rb
Mapexplorer::Application.routes.draw do
  root :controller=> 'application', :action=>'view'
  match '/about', :controller=>'application',:action=>'about'
  match '/view', :controller=>'application',:action=>'view'
  match '/penlakemap', :controller=>'penlakemap',:action=>'view'
  match '/penlakemap/about', :controller=>'penlakemap',:action=>'about'
  match '/penlakemap/downloads', :controller=>'penlakemap',:action=>'downloads'
  match '/penlakemap/points', :controller=>'penlakemap',:action=>'points'
  match '/pgconmap', :controller=>'pgconmap',:action=>'view'
  match '/pgconmap/about', :controller=>'pgconmap',:action=>'about'
  match '/pgconmap/points', :controller=>'pgconmap',:action=>'points'
  match '/pgconmap/interest', :controller=>'pgconmap',:action=>'interest'

  match '/burlingtonrec', :controller=>'burlingtonrec',:action=>'view'
  match '/burlingtonrec/about', :controller=>'burlingtonrec',:action=>'about'
  match '/burlingtonrec/pools', :controller=>'burlingtonrec',:action=>'pools'
  match '/burlingtonrec/splash', :controller=>'burlingtonrec',:action=>'splash'
  match '/burlingtonrec/pools/list', :controller=>'burlingtonrec',:action=>'pools_list'
  match '/burlingtonrec/splash/list', :controller=>'burlingtonrec',:action=>'splash_list'
  

end

app/models/facility.rb
class Facility < ActiveRecord::Base
end

app/models/point.rb
class Point < ActiveRecord::Base
  validates_numericality_of :lat, :lon
end

app/models/web_visit.rb
class WebVisit < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter LogFilter
  def view
    @title = 'MapExplorer - Exploring Communities Through Maps'
    render
  end
  def about
      @title = 'MapExplorer - Exploring Communities Through Maps'
  end
  def penlakemap
    render
  end
end

app/controllers/burlingtonrec_controller.rb
class BurlingtonrecController < ActionController::Base
protect_from_forgery
before_filter LogFilter
 def view
   @title='Burlington & Oakville Recreational Spots'
    render :layout=>'application'
  end
  def about   
    @title='Burlington & Oakville Recreational Spots'
    render :layout=>'application'
  end
 
  def pools 
    @title='Burlington & Oakville Recreational Spots'
    @request_url=burlingtonrec_pools_list_path
    render :action=>'interest',:layout=>'application'
  end
  def splash
    @title='Burlington & Oakville Recreational Spots'
    @request_url=burlingtonrec_splash_list_path
    render :action=>'interest',:layout=>'application'
  end
  def pools_list
    points=Facility.where("facility_type like '%Pool%'").order('name')    
    point_lookup(points)
  end
  def splash_list
    points=Facility.where("facility_type like 'Spray Pad%'").order('name')
    points.order("name")
    point_lookup(points)
  end
  def point_lookup(points)   
    points_array=[]
    points.each do |p|
      url=''
      if p.url != nil
        url=sprintf "<a href=\"%s\">Additional Information</a>" , p.url
      end
      name='Swimming Pool'
      if p.name != nil
        name=p.name
      end
      elem= { 'lat'=>p.lat,
        'lon'=>p.lon,
        'description'=>name + ' ' + url + '<br>source:'+  p.source,
        'name' => name,
        'city' => p.city
      }
      points_array.push(elem)
    end
    @points_json=JSON.generate(points_array)
    render :text=>@points_json
  end
  def interest
    @title='Burlington & Oakville Recreational Spots'
    render :layout=>'application'
  end
end

app/controllers/log_filter.rb
class LogFilter
  def self.filter(controller)
    header=controller.request.headers
    agent = header['HTTP_USER_AGENT']
    referal = header['HTTP_REFERER']
    url = controller.request.url
    client = controller.request.remote_ip
    visit = WebVisit.new(:url=>url,:referal=>referal,:agent=>agent,
                         :client=>client,
                         :date=>DateTime.now())
    visit.save()
  end
end

app/controllers/penlakemap_controller.rb
class PenlakemapController < ActionController::Base
  protect_from_forgery
  before_filter LogFilter
  def view
    @title='Peninsula Lake Map (Huntsville, Ontario)'
    render :layout=>'application'
  end
  def about
    @title='Peninsula Lake Map (Huntsville, Ontario)'
    render :layout=>'application'
  end
  def downloads
    @title='Peninsula Lake Map (Huntsville, Ontario)'
    render :layout=>'application'
  end
  def points
    points=Point.where("point_type='penlakemap'")
    points_array=[]
    points.each do |p|
      elem= { 'lat'=>p.lat,
        'lon'=>p.lon,
        'description'=>p.description
      }
      points_array.push(elem)
    end
    @points_json=JSON.generate(points_array)
    render :text=>@points_json
  end
end

app/controllers/pgconmap_controller.rb
class PgconmapController < ActionController::Base
  protect_from_forgery
  before_filter LogFilter
  def view
    @title='MapExplorer - PGCon Map (Ottawa, Ontario)'
    render :layout=>'application'
  end
  def about
    @title='MapExplorer - PGCon Map (Ottawa, Ontario)'
    render :layout=>'application'
  end
  def points
    points=Point.where("point_type='pgcon'")
    points_array=[]
    points.each do |p|
      elem= { 'lat'=>p.lat,
        'lon'=>p.lon,
        'description'=>p.description
      }
      points_array.push(elem)
    end
    @points_json=JSON.generate(points_array)
    render :text=>@points_json
  end
  def interest
    render :layout=>'application'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/about.html.erb
<div id="container" class="text-block">
<h1>About MapExplorer</h1>
MapExplorer.org is a site dedicated to exploring communities through
customized maps using Open Data.

MapExplorer.org uses <a href="http://www.openstreetmap.org">OpenStreetMap</a>
data combined with local data to explore the themes featured on each map.

<h2>
Contact
</h2>
MapExplorer.org is a project by <a href="http://scanningpages.wordpress.com">Steve  Singer</a>.  You can contact him through 
email at steve@ssinger.info.
</div>

app/views/application/view.html.erb
<div id='image-buttons'>
<ul>
<li>
<%= link_to(image_tag("pgcon.png"),pgconmap_path,:alt => 'PGCON Map')  %>
</li>
<li>
<%= link_to(image_tag("penlakemap.png"),penlakemap_path,:alt => 'Peninsula Lake Map') %>
</li>
<li>
<%= link_to(image_tag("burlington_rec.jpg"),burlingtonrec_path,:alt => 'Burlington & Oakville Recreational Facilities') %>
</li>
</ul>
</div>

app/views/burlingtonrec/_map.html.erb
<div id='map-container' class="map-style">
<h1>Recreational Facilities in Burlington and Oakville</h1>

<div   id="map" ></div>
<script defer="defer" type="text/javascript">
 
  var bounds= new OpenLayers.Bounds(-79.889,43.229,-79.6485,43.5129).transform(new OpenLayers.Projection("EPSG:4326"),new OpenLayers.Projection("EPSG:900913"));
  map = new OpenLayers.Map( 'map', 
  {
    maxExtent: bounds,
    projection: "EPSG:900913",
    units: "degree",
    restrictedExtent:bounds,
    controls : [new OpenLayers.Control.Attribution(),
    new OpenLayers.Control.PanZoomBar(),
    new OpenLayers.Control.Navigation()]  
  });
  
  /**
   * Next we define the base layer for the map.
   * The URL comes from mapbox. 
   */
  var attributes={ 
    attribution: "CC-BY-SA. OpenStreetMap & Contributors",
    sphericalMercator: true,
    minZoomLevel: 11,
    maxZoomLevel: 17,
    numZoomLevels:7,
    zoomOffset: 11,
    //providing the resolutions array is important when
    //using restricted zooms. These numbers can be obtained
    //from the web and are standard resolutions the zooms
    //of a spherical mercator map.
    resolutions: [76.437028271484384,38.218514135742192,19.109257067871096,9.554628533935548, 4.777314266967774, 2.388657133483887, 
    1.1943285667419434],
    units:"degree",
    projection: "EPSG:900913",
  }
  
  layer = new OpenLayers.Layer.XYZ("PGCon Map",
            ["http://a.tiles.mapbox.com/v3/ssinger.map-v62fuwdi/${z}/${x}/${y}.png",
            "http://b.tiles.mapbox.com/v3/ssinger.map-v62fuwdi/${z}/${x}/${y}.png",
            "http://c.tiles.mapbox.com/v3/ssinger.map-v62fuwdi/${z}/${x}/${y}.png"
           ]
  , attributes
  );

  //Add the layer to the map
  map.addLayer(layer);
  map.setCenter( new OpenLayers.LonLat(-79.6945,43.3601).
                     transform(
                     new OpenLayers.Projection("EPSG:4326"),
                     map.getProjectionObject()),1,true,true);
 		     

</script>
<div>
This map contains overlay data that is copyright the City of Burlington. See <a href="http://cms.burlington.ca/AssetFactory.aspx?did=18762"> terms of use</a> for additional restrictions.
</div>

app/views/burlingtonrec/_nav_bar.html.erb
<div id='map-nav-bar' >
<ul>
  <li>
    <%= link_to 'Map', burlingtonrec_path %>
  </li>
 <li>
   <%= link_to 'About', burlingtonrec_about_path %>
 </li>
 <li>
   <%= link_to 'Pools', burlingtonrec_pools_path %>
 </li>
 <li>
   <%= link_to 'Splash Pads', burlingtonrec_splash_path %>
 </li>
</ul>

</div>

app/views/burlingtonrec/about.html.erb
<%= render "map" %>
<div class="text-block"> 

Burlington/Oakville Recreation</a> is a map of recreational facilities in Burlington and Oakville, Ontario.
<p>
Burlington and Oakville are cities in Halton Region, west of Toronto, Ontario, Canada.  Burlington and Oakville are mostly comprised of low to mid density housing and have experienced much development during the past two decades.


<p>
This map shows select recreational facilities in these communities.

<h2>Map Sources</h2>
The Base map is based on <a href="http://www.openstreetmap.org">OpenStreetMap</a> data and is currentl styled using a <a href="http://mapbox.com">Mapbox</a>
style.  The data on recreational facilities comes from the City of Burlington released under the Burlington OpenData pilot and the OpenStreetMap database.



</div>

app/views/burlingtonrec/interest.html.erb
<%= render "map" %>
<script defer="defer" type="text/javascript">

  /**
   * This javascript adds in the list of 'interesting' points'
   * and associated popups.
   */  
  PointClickHandler = function (latlon,description) {
    this.latlon=latlon;
    this.description=description;
  }
  PointClickHandler.prototype.constructor=PointClickHandler;
  PointClickHandler.prototype.onEvent = function(evt) {
    var popup=new OpenLayers.Popup(null,this.latlon,new OpenLayers.Size(300,100),this.description,true);
    map.addPopup(popup);	
  }

  var POIMapping=new Array();

  /**
   * Request the list of points from the server via 
   * an HTTP GET request.
   */
  var client = new XMLHttpRequest();
  client.open("GET",'<%= @request_url %>' ,true);
  client.onreadystatechange=function() {
    if(client.readyState==4 && client.status==200) {
      /**
       *  The response is a JSON array of hashes (or should be)
       */
      var points=JSON.parse(client.responseText);
      var markers = new OpenLayers.Layer.Markers("markers");
      var size = new OpenLayers.Size(21,25);
      var offset = new OpenLayers.Pixel(-(size.w/2), -size.h);
      var icon = new OpenLayers.Icon('/img/marker.png',size,offset);
      map.addLayer(markers);     
      for(var i=0; i < points.length; i++) {
        var p=new OpenLayers.LonLat(points[i]['lon'],points[i]['lat']).transform(new OpenLayers.Projection("EPSG:4326"),new OpenLayers.Projection("EPSG:900913"));
	var marker=new OpenLayers.Marker(p,icon.clone());
        var description=points[i]['description'];
        var name = points[i]['name'];
        /**
         * Create a handler class for each point.  This will have access
         * to the description.  The handler class will display a popup
         * with the description when clicked.
         */
        var eventHandler = new PointClickHandler(p,description);
        marker.events.register('mousedown',eventHandler,eventHandler.onEvent);
        markers.addMarker(marker);

        /**
         * Built up a list of POI's that the user can click on to
         * center the map on the POI. 
         */
        POIMapping[i]=p;		       
        var POI_dom=document.getElementById('poi-list-'+points[i]['city']);
        var li=document.createElement('li');
        var link=document.createElement('a');
        link.appendChild(document.createTextNode(name));
        li.appendChild(link);
        /**
         * The coordinates of each POI are stored in the global array.
         * The event handler for the 'on click' method of each link
         * will lookup those coordinates. 
         */
        link.setAttribute('onclick','map.moveTo(POIMapping[' + i + '],4);');
        POI_dom.appendChild(li);
		       
      }//for
    }//if200
  }//function
  client.send()

</script>
<h3>Burlington</h3>
<ul id='poi-list-Burlington' class='poi-list'>
</ul>

<h3>Oakville</h3>
<ul id='poi-list-Oakville' class='poi-list'>
</ul>

app/views/burlingtonrec/view.html.erb
<%= render "map" %>
<div   id="map" ></div>
<div class="text-block"> 
Recreational Facilities in Burlington and Oakville, Ontario

</div>

app/views/layouts/application.html.erb
<html>
<head>
  <title><%= @title %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
<meta name="description" content="A collection of community OpenStreetMap based maps for Oakville, Burlington,Ottawa,Huntsville Ontario,Peninsula Lake" />
<meta http-equiv="content-language" content="en-ca" />
<link rel="stylesheet" href="../theme/default/style.css" type="text/css">

<script src="/OpenLayers.js"></script>
 <%= csrf_meta_tags %>
 

</head>

<body>
<div id="banner">
<h1>Map Explorer</h1>
<div id="nav-bar">
<ul>
<li><%= link_to 'Maps', view_path(@application) %></li>
<li><%= link_to 'About', about_path(@application) %></li>
</ul>
</div>
</div>
<div id="body-container">
<%= render "nav_bar" %>
<div id="content-container">
<%= yield %>
<div class="map-extra-pane">
</div>
</div>
</div>
<div id="footer">
</div>
</body>
</html>

app/views/penlakemap/_map.html.erb
<div id='map-container' class="map-style">
<div   id="map" ></div>
</div>
<script defer="defer" type="text/javascript">
  var map, layer;
  var bounds= new OpenLayers.Bounds(-79.2274,45.3087,-79.0338,45.3666).transform(new OpenLayers.Projection("EPSG:4326"),new OpenLayers.Projection("EPSG:900913"));
  map = new OpenLayers.Map( 'map', 
  {
  maxExtent:bounds,
  projection: "EPSG:900913",
  units: "degree",
  restrictedExtent: bounds,
  controls : [new OpenLayers.Control.Attribution(),
  new OpenLayers.Control.PanZoomBar(),
  new OpenLayers.Control.Navigation()]
  
  });
  layer = new OpenLayers.Layer.XYZ("Penlake Map",
  ["http://a.tiles.mapbox.com/v3/ssinger.penlake/${z}/${x}/${y}.png",
  "http://b.tiles.mapbox.com/v3/ssinger.penlake/${z}/${x}/${y}.png",
  "http://c.tiles.mapbox.com/v3/ssinger.penlake/${z}/${x}/${y}.png"
  ]
  , { attribution: "CC-BY-SA. OpenStreetMap & Contributors + Canadian Hydrological Service. NOT FOR NAVIGATION",
  sphericalMercator: true,
  minZoomLevel: 13,
  maxZoomLevel: 17,
  numZoomLevels:5,
  zoomOffset: 13,
  resolutions: [ 19.109257067871095, 
  9.554628533935547, 4.777314266967774, 2.388657133483887, 
  1.1943285667419434],
  units:"degree",
  projection: "EPSG:900913",
  }
  );
  map.addLayer(layer);
  map.setCenter(
  new OpenLayers.LonLat(-79.12715,45.36535).transform(
  new OpenLayers.Projection("EPSG:4326"),
  map.getProjectionObject()),1,true,true);
  var client = new XMLHttpRequest();
  client.open("GET",'<%= penlakemap_points_path %>' ,true);
  client.onreadystatechange=function() {
  if(client.readyState==4 && client.status==200) {
    var points=JSON.parse(client.responseText);
    var markers = new OpenLayers.Layer.Markers("markers");
    var size = new OpenLayers.Size(21,25);
    var offset = new OpenLayers.Pixel(-(size.w/2), -size.h);
    var icon = new OpenLayers.Icon('img/marker.png',size,offset);
    map.addLayer(markers);
    for(var i=0; i < points.length; i++) {
		     var p=new OpenLayers.LonLat(points[i]['lon'],points[i]['lat']).transform(new OpenLayers.Projection("EPSG:4326"),new OpenLayers.Projection("EPSG:900913"));
		     var marker=new OpenLayers.Marker(p,icon.clone());
		     var description=points[i]['description'];
		     marker.events.register('mousedown',marker,function(evt) {
		     var popup=new OpenLayers.Popup(i,p,new OpenLayers.Size(100,50),description,true);
		     map.addPopup(popup);		   
		     });
		     markers.addMarker(marker);
		     
		     }//for
		     
		     }//if200
		     }//function
	client.send()
		     

</script>
	

app/views/penlakemap/_nav_bar.html.erb
<div id='map-nav-bar' >
<ul>
  <li>
    <%= link_to 'Penlake Map', penlakemap_path %>
  </li>
 <li>
   <%= link_to 'About', penlakemap_about_path %>
 </li>
 <li>
   <a href="http://scanningpages.wordpress.com/tag/penlakemap">Blog</a>
 </li>
 <li> <%= link_to 'Downloads', penlakemap_downloads_path %>
</ul>

</div>

app/views/penlakemap/about.html.erb
<h1>Peninsula Lake Map (Pen Lake), Huntsville Ontario</h1>
<%= render "map" %>
<div class="text-block"> 


<h2>What Is The Peninsula Lake Map</h2>
The Peninsula Lake Map is a free community built  map of Peninsula lake based on a combination of OpenStreetMap data and depth data from Canadian Hydrological Service.

<h2>What Map Features are included</h2>
The Peninsula Lake Map contains a map of the lake including depth data, recreational facilities such as skiing, tennis courts and golf.  
Hotels are also included on the map

<h2>What Do you mean by "Free"</h2>
The Peninsula Lake Map is released under the CC-BYS-A  license.   This means that you are free to:

    Print the map as many times as you want
    Ad your companies logo to the map and sell it
    Upload the map data to your GPS unit
    Change the map as long as the changes are released under CC-BY-SA
    Include the map in a book or as part of another web site

As long as you comply with the terms of the CC-BY-SA license which include crediting "OpenStreetMap & Contributors" and the "Canadian Hydrological Service" and share any changes you make to the map.

<h2>Where Does Data Come From</h2>
In the spring and summer of 2009 the Canadian Hydrological service conducted a survey of Peninsula and Fairy lakes in preparation for the G8 summit that was held at Deerhurst Resort in 2010.  The depth data in this map is based on that survey work.

The rest of the map is based on the OpenStreetMap project.  OpenStreetMap is buiding an editable wiki-style map of th eworld.  Data in the Huntsville area includes data collected by volunteers with handheld GPS units, traces of satellite images and data released by Natural Resources Canada.

<h2>How Can I Help</h2>
You can help by adding points of interest to the map.  You can either do this by adding them directly to OpenStreetMap (www.openstreetmap.org) or by emailing the GPS coordinates  along with a description to steve@ssinger.info.  In particular we would like to add

    The location of bouys and navigation aids
    The location of rocks trees and other underwater hazards
    The names of any unamed bays or islands but please don't copy these from another map

Email us If you have made significant updates to the map and would like new copies of the files generated.
What Do the Depth Numbers Mean
The depth numbers on the map are in feet (meters in the Oct 2010 edition) and indicate the distance from the high-water mark at Huntsville (The sounding datum) to the lake floor.  The sounding datum is 281.8 meters (913 feet).   This means that if in your boat over point on the map marked 10 and your GPS receiver says that your current altitude is 913.0 (feet) then you should expect 10 feet  of water below you.

<h2>Is More Depth Data Available</h2>

Yes.  The Canadian Hydrological Service collected a data point every one meter for much of the two lakes.  They have released a subset of this data, one point every 100 meters to us.    The printed version of the map only includes "interesting" points to not appear cluttered.    The files for GPS units will contain all of the data points released to us  you will also be able to download the raw data files (100m) in OpenStreetMap format from us.      The complete 1m resolution data is available for purchase from the Canadian Hydrological Service.

<h2>Why Is There No Data In Some Places</h2>
The Bay near Deerhurst Resort (north west) and the bay at the South East of the lake were not surveyed by the Canadian Hydrological Service because the water was deemed to be too shallow for them to work.   These areas remain uncharted.   Feel free to send in any observations you have of for these areas.

<h2>Where Do The Contour Lines Come From</h2>

The contour lines were interpolated with software based on the 100m soundings from the Canadian Hydrological Service.  They do not show the exact profile of the lake bed.

<h2>I Hit a Rock While Using The Map</h2>

The Pen Lake Map is clearly marked as "NOT FOR NAVIGATION" and "USE AT YOUR OWN RISK".   You were warned. Feel free to add any hazards you  survey  to the OpenStreetMap.
</div>

app/views/penlakemap/downloads.html.erb
<h1>Peninsula Lake, Huntsville Ontario</h1>
<%= render "map" %>
<div class="text-block"> 
<h1>Downloads</h1>
<ul>
<li> <a href="http://sourceforge.net/projects/penlakemap/files/penlake.2012.05.svg/download">Peninsula Lake May 2012 - SVG</a></li>
<li> <a href="http://sourceforge.net/projects/penlakemap/files/penlake.2012.05.pdf/download"</a>Peninsula Lake May 2012 - PDF</a></li>
<li> <a href="https://scanningpages.files.wordpress.com/2012/05/penlake-2012-05.png">Peninsula Lake May 2012 - PNG</a></li>
</ul>

</div>

app/views/penlakemap/view.html.erb
<h1>Peninsula Lake Map, Huntsville Ontario</h1>

<%= render "map" %>
<meta name="description" content="Explore Peninsula Lake(PenLake), Huntsville, Ontario, Canada with a map. The map also includes Fairy lake">
<div   id="map" ></div>
<div class="text-block"> 
Peninsula Lake is a mid-sized lake near Huntsville, Ontario, Canada that
is surronded by cottages, homes and resorts.
<p>
Most of Fairy lake is included in this map as well.  Fairy lake is the
larger lake to the west of the map

</div>

app/views/pgconmap/_map.html.erb
<div id='map-container' class="map-style">
<div   id="map" ></div>
</div>
<script defer="defer" type="text/javascript">
  /**
   * This code displays the main PGCON map.
   * The map will be displayed inside of the div 'map' defined above.
   */
  var map, layer;
  /**
   *  We define the bounding box for the map.  We specifiy this box in
   *  WGS 84 Lat/Lon coordinates but we must convert it to Spherical Mercator
   *  since our map is in Spherical Mercator (epsg:900913)
   */
  var bounds= new OpenLayers.Bounds(-75.7001,45.4166,-75.674,45.435).transform(new OpenLayers.Projection("EPSG:4326"),new OpenLayers.Projection("EPSG:900913"));
  map = new OpenLayers.Map( 'map', 
  {
    maxExtent: bounds,
    projection: "EPSG:900913",
    units: "degree",
    restrictedExtent:bounds,
    controls : [new OpenLayers.Control.Attribution(),
    new OpenLayers.Control.PanZoomBar(),
    new OpenLayers.Control.Navigation()]  
  });
  
  /**
   * Next we define the base layer for the map.
   * The URL comes from mapbox. 
   */
  var attributes={ 
    attribution: "CC-BY-SA. OpenStreetMap & Contributors",
    sphericalMercator: true,
    minZoomLevel: 15,
    maxZoomLevel: 18,
    numZoomLevels:4,
    zoomOffset: 15,
    //providing the resolutions array is important when
    //using restricted zooms. These numbers can be obtained
    //from the web and are standard resolutions the zooms
    //of a spherical mercator map.
    resolutions: [ 4.777314266967774, 2.388657133483887, 
    1.1943285667419434, 0.597164283],
    units:"degree",
    projection: "EPSG:900913",
  }
  
  layer = new OpenLayers.Layer.XYZ("PGCon Map",
            ["http://a.tiles.mapbox.com/v3/ssinger.pgcon/${z}/${x}/${y}.png",
            "http://b.tiles.mapbox.com/v3/ssinger.pgcon/${z}/${x}/${y}.png",
            "http://c.tiles.mapbox.com/v3/ssinger.pgcon/${z}/${x}/${y}.png"
           ]
  , attributes
  );

  //Add the layer to the map
  map.addLayer(layer);
  map.setCenter( new OpenLayers.LonLat(-75.68715,45.424).
                     transform(
                     new OpenLayers.Projection("EPSG:4326"),
                     map.getProjectionObject()),1,true,true);
 		     

</script>
	

app/views/pgconmap/_nav_bar.html.erb
<div id='map-nav-bar' >
<ul>
  <li>
    <%= link_to 'PGCon Map', pgconmap_path %>
  </li>
 <li>
   <%= link_to 'About', pgconmap_about_path %>
 </li>
 <li>
   <%= link_to 'Points of Interest', pgconmap_interest_path %>
 </li>
</ul>

</div>

app/views/pgconmap/about.html.erb
<%= render "map" %>
<div class="text-block"> 
<h1>PGCon Map</h1>

<a href="http://www.pgcon.org">PGCON</a> is an annual <a href="http://www.postgresql.org">PostgreSQL</a> developers conference held in Ottawa, Ontario, Canada every May. PGCon is held at the University of Ottawa.

<p>
This map shows the area around the conference and highlights places that
conference attendees might be interested in.

</div>

app/views/pgconmap/interest.html.erb
<%= render "map" %>
<script defer="defer" type="text/javascript">

  /**
   * This javascript adds in the list of 'interesting' points'
   * and associated popups.
   */  
  PointClickHandler = function (latlon,description) {
    this.latlon=latlon;
    this.description=description;
  }
  PointClickHandler.prototype.constructor=PointClickHandler;
  PointClickHandler.prototype.onEvent = function(evt) {
    var popup=new OpenLayers.Popup(null,this.latlon,new OpenLayers.Size(100,50),this.description,true);
    map.addPopup(popup);	
  }

  var POIMapping=new Array();

  /**
   * Request the list of points from the server via 
   * an HTTP GET request.
   */
  var client = new XMLHttpRequest();
  client.open("GET",'<%= pgconmap_points_path %>' ,true);
  client.onreadystatechange=function() {
    if(client.readyState==4 && client.status==200) {
      /**
       *  The response is a JSON array of hashes (or should be)
       */
      var points=JSON.parse(client.responseText);
      var markers = new OpenLayers.Layer.Markers("markers");
      var size = new OpenLayers.Size(21,25);
      var offset = new OpenLayers.Pixel(-(size.w/2), -size.h);
      var icon = new OpenLayers.Icon('/img/marker.png',size,offset);
      map.addLayer(markers);     
      for(var i=0; i < points.length; i++) {
        var p=new OpenLayers.LonLat(points[i]['lon'],points[i]['lat']).transform(new OpenLayers.Projection("EPSG:4326"),new OpenLayers.Projection("EPSG:900913"));
	var marker=new OpenLayers.Marker(p,icon.clone());
        var description=points[i]['description'];
        /**
         * Create a handler class for each point.  This will have access
         * to the description.  The handler class will display a popup
         * with the description when clicked.
         */
        var eventHandler = new PointClickHandler(p,description);
        marker.events.register('mousedown',eventHandler,eventHandler.onEvent);
        markers.addMarker(marker);

        /**
         * Built up a list of POI's that the user can click on to
         * center the map on the POI. 
         */
        POIMapping[i]=p;		       
        var POI_dom=document.getElementById('poi-list');
        var li=document.createElement('li');
        var link=document.createElement('a');
        link.appendChild(document.createTextNode(description));
        li.appendChild(link);
        /**
         * The coordinates of each POI are stored in the global array.
         * The event handler for the 'on click' method of each link
         * will lookup those coordinates. 
         */
        link.setAttribute('onclick','map.setCenter(POIMapping[' + i + '])');
        POI_dom.appendChild(li);
		       
      }//for
    }//if200
  }//function
  client.send()

</script>

<ul id='poi-list'>

</ul>

app/views/pgconmap/view.html.erb
<%= render "map" %>
<div   id="map" ></div>
<div class="text-block"> 
A Map for PGCon Attendees
</div>